name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    required: false
    description: GitHub token
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
